### ISSUE TITLE
Components Functionality Checklist

### ISSUE THREAD

**Issue by natoshiadumont** [Tripple-Scoop/Nice_Cream#47]
The attached descriptions for each component  were discussed on our March 5th meeting. Before merging to our main branch, each component must be up for review/testing.

**Home**

- [ ] Shop Now!
- [ ] Log In/Register/Profile
- [ ] Our Story

**My Cart**

- [ ] Order Items (name, image, price, delete, update quantity)
- [ ] "Checkout" button link to Checkout page
- [ ] Keep Shopping (link back to Products page)

**Checkout**

- [ ] Fetch order items by order_id
- [ ] Select payment type from dropdown
- [ ] Shipping/Billing address input (if logged in, auto-fill billing address)
- [ ] Is shipping address different from billing checkbox: if so, type in new address.
- [ ] On submit, set order order to "fulfilled", "Thanks for your order!" confirmation page w/ links (if logged in "Go to My Profile", "Keep Shopping!" )

**Profile**
- [ ] Edit Profile
- [ ] Past Orders
- [ ] Link to My Cart
- [ ] Admin-Specific Page (all customer orders, all customer's info, add/remove/update product)

**Products**

- [ ] FetchAllProducts (clicking links to item specific page w/reviews)
- [ ] AdminONLY (delete, add, or update flavor options)
- [ ] Filter by flavor type
- [ ] Search bar (search by flavor or type)
